### ISSUE TITLE
Stránky slovník.gov.cz - zaměření motivace na legislativu

### ISSUE THREAD

**Issue by bindeali** [datagov-cz/ssp#660]
Na stránkách slovník.gov.cz, které vychází ze souboru https://github.com/datagov-cz/ssp/blob/master/docs/index.md, se prvních pár motivačních odstavců zmiňuje o využití SSP pro popis pojmů z legislativy. To je v pořádku, ale na jedné schůzce se mi stalo, že SSP a přeneseně i Výrobní linku chápali jako nástroje _pouze_ pro legislativní slovníky a žádné jiné. Chtěla bych se zeptat na názor, jestli

* je to vůbec problém, který stojí za to řešit (koneckonců, letmé prohlížení ShowITa by jim tuto představu jednoznačně vyvrátilo),
* a pokud ano, jak ho vyřešit (myslím, že jedna doplňující věta by stačila).

**Comment by MichalMed** [comment]
Podle mě to na základě jedné zpětné vazby problém není, ovšem pokud bysme to chteli měnit, pak bych raději přidal celý odstavec, který by popisoval další usecasy SSP i VL.
